# Generated by Django 4.2.11 on 2024-03-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/products/')),
                ('name', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('category', models.CharField(default='', max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
        ),
    ]
